// Regenerate src/psl-data.ts from a pinned commit of the Public Suffix List (MPL-2.0).
// Usage: node scripts/update-psl.mjs <commit-sha>
import {writeFile} from 'node:fs/promises';
import {domainToASCII} from 'node:url';
import {createHash} from 'node:crypto';
const commit=process.argv[2];
if(!/^[0-9a-f]{40}$/.test(commit??''))throw new Error('Pass a full publicsuffix/list commit SHA.');
const base=`https://raw.githubusercontent.com/publicsuffix/list/${commit}`;
const text=await (await fetch(`${base}/public_suffix_list.dat`,{redirect:'error'})).text();
if(!text.includes('===BEGIN PRIVATE DOMAINS==='))throw new Error('Unexpected list content.');
const rules=[];
for(const raw of text.split('\n')){
  const line=raw.trim();
  if(!line||line.startsWith('//'))continue;
  const exception=line.startsWith('!'),body=exception?line.slice(1):line;
  const ascii=body.split('.').map(label=>label==='*'?'*':domainToASCII(label)).join('.');
  if(!ascii||ascii.includes('..'))throw new Error(`Bad rule: ${line}`);
  rules.push((exception?'!':'')+ascii.toLowerCase());
}
const sha256=createHash('sha256').update(text).digest('hex');
await writeFile('src/psl-data.ts',`// Generated by scripts/update-psl.mjs from publicsuffix/list ${commit} (MPL-2.0; see runtime/licenses/publicsuffix-list-LICENSE).\n// Source SHA-256: ${sha256}. ICANN and private sections, IDN rules converted to punycode.\nexport const PSL_COMMIT:string='${commit}';\nexport const PSL_RULES:string=${JSON.stringify(rules.join(' '))};\n`);
await writeFile('runtime/licenses/publicsuffix-list-LICENSE',await (await fetch(`${base}/LICENSE`,{redirect:'error'})).text());
console.log(`${rules.length} rules from ${commit}`);
